{% set version = "0.1.9" %}

package:
  name: tsvfmt
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  host:
    - go

test:
  commands:
    - tsv -h 2>&1 | grep -q Usage

about:
  home: "https://github.com/vladsaveliev/tsvfmt"
  license: MIT
  summary: Tab-separated file viewer for command line
