name: CI
on: [push, pull_request]

jobs:
  build_and_test:
    # For tag pushes, we want to assure only the tag event triggers CI, not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    name: Build and run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            executable_suffix: 'linux'
          - os: macos-latest
            executable_suffix: 'macos'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@v2

      - name: Compile
        run: go build tsv.go

      - name: Install & test
        run: |
          export PATH=${{ github.workspace }}:$PATH
          bash -ex test/test.sh

      # To share the artifact with other jobs
      - uses: actions/upload-artifact@master
        with:
          name: asset_${{ matrix.executable_suffix }}.zip
          path: ${{ github.workspace }}/tsv
          if-no-files-found: error

  # In a separate job w/o matrix because we don't want a release for each OS
  initialize_gh_release:
    # Only creating releases on tag pushes
    if: "startsWith(github.ref, 'refs/tags/')"
    name: Initialize GitHub release
    needs: build_and_test
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_gh_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_gh_release
        uses: actions/create-release@v1
        env:  # This token is provided by Actions, you don't need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  upload_gh_assets:
    if: "startsWith(github.ref, 'refs/tags/')"
    name: Publish GitHub release assets
    needs: initialize_gh_release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            executable_suffix: 'linux'
          - os: macos-latest
            executable_suffix: 'macos'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: asset_${{ matrix.executable_suffix }}.zip
          path: ./

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:  # This token is provided by Actions, you don't need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.initialize_gh_release.outputs.upload_url }}
          asset_path: ./tsv
          asset_name: tsv_${{ matrix.executable_suffix }}
          asset_content_type: application/octet-stream

  conda:
    if: "startsWith(github.ref, 'refs/tags/')"
    name: Build and publish a conda package
    needs: build_and_test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@master

      - name: Add miniconda to PATH
        run: echo "PATH=${HOME}/miniconda/bin:${PATH}" >> $GITHUB_ENV

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildenv
          channels: vladsaveliev,conda-forge,defaults
          channel-priority: true
          mamba-version: "*"

      - name: Setup conda
        run: mamba install conda-build anaconda-client

      - name: Build package
        run: |
          mamba build conda/$(basename $GITHUB_REPOSITORY)
          mamba install --use-local $(basename $GITHUB_REPOSITORY)

      - name: Test
        run: bash -ex test/test.sh

      - name: Upload to anaconda
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
            upload ${HOME}/miniconda/conda-bld/**/*.tar.bz2
