name: CI
on: [push, pull_request]

jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI,
    # not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@master

      - name: Add miniconda to PATH
        run: echo "PATH=${HOME}/miniconda/bin:${PATH}" >> $GITHUB_ENV

      - name: Setup conda
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
              --no-verbose -O miniconda.sh
          else
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh \
              --no-verbose -O miniconda.sh
          fi
          bash miniconda.sh -b -p ~/miniconda
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge --add channels vladsaveliev
          conda install conda-build conda-verify anaconda-client go

      - name: Build package
        run: conda build conda/$(basename $GITHUB_REPOSITORY)

      - name: Install
        run: conda install --use-local $(basename $GITHUB_REPOSITORY)

      - name: Test
        run: |
          bash -e test/test.sh
          
      - name: Upload to anaconda
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
            upload ${HOME}/miniconda/conda-bld/**/*.tar.bz2
